### PR TITLE
Fixed the 500 bug when input validation was false on cb login page

### LINKED ISSUE #207: 🐛cb login servers error page when theres no input fields
On current master 👇 

p2c-bug-1

Bug seems to be a frontend/react issue as server does the thing it's _currently_ meant to...

### PR DESCRIPTION
**Pull request by RogeredBacon**
Fixed the bug that was causing a 500 error whenever the input validation returned false. The res.send() was wrongly formatted and the error messages were backwards also.

Fixes #207

### CODE REVIEW

**Comment by RogeredBacon** [comment]
I had some trouble with prettier removing/adding parentheses, are you guys using the prettier-eslint?

**Comment by astroash** [comment]
👍

**Comment by astroash** [comment]
👍

**Comment by astroash** [comment]
🙈

**Comment by astroash** [comment]
🙈

**Comment by eliascodes** [comment]
@RogeredBacon I'm not using prettier, I just have the normal eslint vscode plugin installed

**Pull request merged**
