### PR TITLE
🐛 fix broken cb signup form

### PR DESCRIPTION
**Pull request by eliascodes**
Fix broken signup form

### CODE REVIEW

**Comment by RogeredBacon** [comment]
screenshot-2018-4-6 data power

Are the error messages meant to look like this? If I was a user I'd have no idea what they were talking about.

**Comment by eliascodes** [comment]
@RogeredBacon fair point, will provide better ones.

**Comment by eliascodes** [comment]
@RogeredBacon try now

**Comment by RogeredBacon** [comment]
Nice, the error messages are great! However I'm getting a 409 error now, when I try to register a CB with the same email as one already registered, and then redirected to the error/unknown 404 page.

**Comment by eliascodes** [comment]
Fixed

**Pull request merged**
